databases:
  - name: mastery_blog
    databaseName: mastery_blog
    user: mastery_blog_user

services:
  - type: web
    name: blog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mastery_blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
