name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: blog_2_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/blog_2_test"
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
          bundler-cache: true   
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Compile code
        run: bin/rails webpacker:compile
      - name: Setup Test Database
        env:
            RAILS_ENV: test 
            POSTGRES_DB: blog_2_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: bin/rails db:migrate
      - name: Run tests
        run: bundle exec rake
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
      
      # - name: Code Climate Coverage
        # uses: paambaati/codeclimate-action@v3.0.0
        # env:
          # CC_TEST_REPORTER_ID: 
        # with:
          # coverageLocations: ${{github.workspace}}/coverage/coverage.xml:cobertura

