name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: blog_2_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/blog_2_test"
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          
      - name: Install dependencies
        run: bundle install

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Setup Database
        run: bin/rails db:migrate

      - name: Compile code
        env:
          RAILS_ENV: test
        run: bin/rails webpacker:compile

      - name: Run tests
        run: bundle exec rake
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
