name: intial-setup-and-test-workflow
on: push

jobs:
  tests:
    name: RSpec Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Setup Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Setup database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
        run: bin/rails db:create db:migrate

      - name: Compile code
        run: bin/rails webpacker:compile
        env:
          RAILS_ENV: test
      
      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
        run:
          bundle exec rails db:setup

      - name: Send coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          verbose: true
